spring:
 # thymeleaf 参数
  thymeleaf:
    cache: false

  profiles:
    active: prod

#logback参数
logging:
  config: classpath:logback-spring.xml


#分页插件参数
pagehelper:
  params: countSql
  reasonable: true
  support-methods-arguments: true
server:
  servlet:
    context-path: /SpringBoot



student:
    name : tpw
    age: 20
    id: 20201028
